/*!

\page create_wire_page Wire

\n To create a \b Wire in the <b>Main Menu</b> select <b>New Entity - > Build - > Wire</b>

\n You can create a \b Wire from several connected edges or wires by
selecting them in the object browser or in the viewer holding Shift
button.

It is possible to select wires or edges from objects. To specify sub-shape type, use
the <b>Object Type</b> radio buttons.

Select \b Tolerance which will be used to check the
connections. If the \b Tolerance value is more than 1e-07, and a gap
within this tolerance is detected, the corresponding edges will be modified to
connect in the middle of the gap.
\n The \b Result will be a \b GEOM_Object (WIRE).

\n <b>TUI Command:</b> <em>geompy.MakeWire(ListOfShape, Tolerance)</em>

<b>Arguments:</b> Name + List of connected wires or edges + Tolerance.

\n <b>Dialog Box:</b>

\image html neo-obj3.png

\n <b>Example:</b>

\image html wiresn.png "Wire"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_wire "Advanced Geometric Objects".

*/
