/*!

\page create_line_page Line

To create a \b Line in the <b>Main Menu</b> select <b>New Entity - >Basic - > Line</b>


There are 2 algorithms to create a \b Line in the 3D space.
The Result of each operation will be a GEOM_Object (edge).

\n Firstly you can define a \b Line by \b Point1 and \b Point2,
which are the points through  which the \b Line passes.
\n <b>TUI Command:</b> <em>geompy.MakeLineTwoPnt(Point1, Point2)</em>
\n <b>Arguments:</b> Name + 2 vertices.

\image html line1.png

\n Secondly you can define a \b Line as intersection of  \b Plane1 and
\b Plane2.
\n <b>TUI Command:</b> <em>geompy.MakeLineTwoFaces(myFace1, myFace2)</em>
\n <b>Arguments:</b> Name + 2 faces.

\image html line2.png


<b>Example:</b>

\image html lines.png "Line defined through points"

\b NB! There is another way to create a line, which is currently
accessible only via \b TUI commands.

You can define a line  passing through the given \b Point and parallel
to the given \b Vector.
\n <b>TUI Command:</b> <em>geompy.MakeLine(Point, Vector)</em>

Our <b>TUI Scripts</b> provide you with useful examples of creation of
\ref tui_creation_line "Basic Geometric Objects".

*/